# -*- coding: utf-8 -*-
"""customer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PzkqAINE3IQlS3qXYXyFFgCZYH5b-Iui
"""

from google.colab import files
files.upload()

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
# %matplotlib inline

df =pd.read_csv("/content/Mall_Customers.csv")

df

df.rename(columns={'Gender':'gender','Age':'age','Annual Income (k$)':'income','Spending Score (1-100)':'score'},inplace=True)

df

df.shape

df.isnull().values.any()

df.describe()

seaborn.pairplot(df[['age','income','score']])

import sklearn.cluster as cluster

kmeans =cluster.KMeans(n_clusters=5)

kmeans = kmeans.fit(df[['income','score']])

kmeans.cluster_centers_

df['income_cluster'] = kmeans.labels_

print(df)

df['income_cluster'].value_counts()

seaborn.scatterplot(x='income',y='score',hue='income_cluster',data=df)

kmeans =cluster.KMeans(n_clusters=2)
kmeans = kmeans.fit(df[['age','score']])
kmeans.cluster_centers_

df['age_cluster'] = kmeans.labels_

print(df)

df['age_cluster'].value_counts()

print(df)

seaborn.scatterplot(x='age',y='score',hue='age_cluster',data=df)

df.loc[df['gender']=='Male','gender']= 1
df.loc[df['gender']=='Female','gender']= 0

df

kmeans =cluster.KMeans(n_clusters=2)
kmeans = kmeans.fit(df[['gender','score']])
kmeans.cluster_centers_

df['gender_cluster'] = kmeans.labels_

print(df)

df['gender'].value_counts()

seaborn.scatterplot(x='gender',y='score',hue='gender_cluster',data=df)